version: '3.2'

services:

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - reverse_proxy
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
    command: npm run start
    networks:
      - reverse_proxy
    depends_on: 
       - db

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: db
    tty: true
    restart: always
    volumes: 
      - ./mysql:/app
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    driver: bridge